// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnqBVr8LM0fIepRsep5NXSTWXt70sLVqc',
    appId: '1:213513650366:web:b889502605353fc3989eef',
    messagingSenderId: '213513650366',
    projectId: 'mynameis-8a83a',
    authDomain: 'mynameis-8a83a.firebaseapp.com',
    storageBucket: 'mynameis-8a83a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdo___DwGgrttTiFpKscwzuAKvvBGzVd0',
    appId: '1:213513650366:android:5111a5dac65aa386989eef',
    messagingSenderId: '213513650366',
    projectId: 'mynameis-8a83a',
    storageBucket: 'mynameis-8a83a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmeASUvsylgeim3d8EzibpL36n6wwpk5E',
    appId: '1:213513650366:ios:ec0d79b15b799da5989eef',
    messagingSenderId: '213513650366',
    projectId: 'mynameis-8a83a',
    storageBucket: 'mynameis-8a83a.appspot.com',
    iosClientId: '213513650366-135mjq7pd2lp9cbn3r1icuer2c9e1778.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNameIs',
  );
}
